name: Train Models

on:
  push:
     branches:
       - 'train-models'
  workflow_dispatch: {}
  schedule:
    - cron: '0 5 * * 2' # This cron schedule runs every Tuesday at 5 AM (UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check commit message
      run: |
        if git log -1 --pretty=%B | grep -q "AUTO"; then exit 0 fi
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Run main.py
      run: python main.py

    - name: Upload 63 model
      uses: actions/upload-artifact@v2
      with:
        name: ps-63
        path: data/ps_63_model.joblib
    - name: Upload GAM model
      uses: actions/upload-artifact@v2
      with:
        name: ps-gam
        path: data/ps_gam_model.joblib
    - name: Update README
      run: |
        python update_readme.py
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add results.md
        git commit -m "AUTO: Updated results"        

    - name: Push changes
      run: git push origin "${{ github.ref }}" # push to the current branch